"""Add Gemini API key to ApiKey model

Revision ID: 133a40845684
Revises: add_recurring_post_schedule
Create Date: 2025-05-23 23:54:01.517462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133a40845684'
down_revision = 'add_recurring_post_schedule'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gemini_api_key', sa.String(length=256), nullable=True))
        batch_op.drop_index('ix_api_key_portal_user_id')

    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'portal_user', ['portal_user_id'], ['id'])

    with op.batch_alter_table('knowledge_document', schema=None) as batch_op:
        batch_op.alter_column('chunk_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('recurring_post_schedule', schema=None) as batch_op:
        batch_op.drop_index('ix_recurring_post_schedule_managed_account_id')
        batch_op.drop_index('ix_recurring_post_schedule_portal_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_post_schedule', schema=None) as batch_op:
        batch_op.create_index('ix_recurring_post_schedule_portal_user_id', ['portal_user_id'], unique=False)
        batch_op.create_index('ix_recurring_post_schedule_managed_account_id', ['managed_account_id'], unique=False)

    with op.batch_alter_table('knowledge_document', schema=None) as batch_op:
        batch_op.alter_column('chunk_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index('ix_api_key_portal_user_id', ['portal_user_id'], unique=1)
        batch_op.drop_column('gemini_api_key')

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
