"""initial setup with portal_user_id on ScheduledPost

Revision ID: bab2afd5c5ff
Revises: 
Create Date: 2025-05-11 14:27:10.989723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab2afd5c5ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portal_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_portal_user_username'), ['username'], unique=True)

    op.create_table('knowledge_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managed_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_user_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('account_id_on_platform', sa.String(length=255), nullable=False),
    sa.Column('account_display_name', sa.String(length=255), nullable=True),
    sa.Column('encrypted_access_token', sa.String(length=1024), nullable=True),
    sa.Column('encrypted_access_token_secret', sa.String(length=1024), nullable=True),
    sa.Column('encrypted_refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managed_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_account_account_id_on_platform'), ['account_id_on_platform'], unique=False)

    op.create_table('action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_user_id', sa.Integer(), nullable=True),
    sa.Column('managed_account_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['managed_account_id'], ['managed_account.id'], ),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('comment_automation_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_user_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('monitored_x_accounts', sa.Text(), nullable=True),
    sa.Column('default_posting_managed_account_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_posting_managed_account_id'], ['managed_account.id'], ),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('managed_account_id_to_post_from', sa.Integer(), nullable=False),
    sa.Column('target_platform', sa.String(length=50), nullable=True),
    sa.Column('target_post_id_on_platform', sa.String(length=255), nullable=False),
    sa.Column('target_post_content', sa.Text(), nullable=True),
    sa.Column('target_post_author', sa.String(length=255), nullable=True),
    sa.Column('target_post_url', sa.String(length=1024), nullable=True),
    sa.Column('suggested_comment_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('platform_comment_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['managed_account_id_to_post_from'], ['managed_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('faiss_index_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunk_faiss_index_id'), ['faiss_index_id'], unique=False)

    op.create_table('scheduled_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_user_id', sa.Integer(), nullable=False),
    sa.Column('managed_account_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.String(length=1024), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['managed_account_id'], ['managed_account.id'], ),
    sa.ForeignKeyConstraint(['portal_user_id'], ['portal_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_post_portal_user_id'), ['portal_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_post_scheduled_time'), ['scheduled_time'], unique=False)

    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    with op.batch_alter_table('scheduled_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_post_scheduled_time'))
        batch_op.drop_index(batch_op.f('ix_scheduled_post_portal_user_id'))

    op.drop_table('scheduled_post')
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunk_faiss_index_id'))

    op.drop_table('knowledge_chunk')
    op.drop_table('generated_comment')
    op.drop_table('comment_automation_setting')
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_log_timestamp'))

    op.drop_table('action_log')
    with op.batch_alter_table('managed_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_account_account_id_on_platform'))

    op.drop_table('managed_account')
    op.drop_table('knowledge_document')
    with op.batch_alter_table('portal_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_user_username'))
        batch_op.drop_index(batch_op.f('ix_portal_user_email'))

    op.drop_table('portal_user')
    # ### end Alembic commands ###
